lv00[]="kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk its kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk xxx kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk";
"kkk kkk kkk",
"kkk kkk kkk";

lv01[]="kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk its kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk";
"kkk kkk kkk",
"kkk kkk kkk";

lv1[]="kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk its kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk xxx kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk";
"kkk kkk kkk",
"kkk kkk kkk",

lv2[]="kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk ptW",
"its kkk kkk",
"kkk xxx kkk",
"ptW kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk xxx kkk",
"ptW kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk";

lv3[]="kkk kkk kkk",
"its kkk kkk",
"kkk kkk kkk",
"ptW kkk kkk",
"kkk kkk kkk",
"kkk xxx kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"xxx kkk kkk",
"kkk kkk kkk",
"ptW kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk";

lv4[]="kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk its kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk ptB kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk xxx kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk ptB kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk";

lv5[]="kkk its kkk",
"kkk ptB kkk",
"kkk kkk ptW",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk ptB",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk ptW",
"kkk kkk kkk",
"kkk kkk xxx",
"kkk kkk ptW",
"kkk kkk kkk",
"kkk kkk ptW",
"kkk kkk kkk",
"kkk kkk ptW",
"kkk xxx kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk";

lv6[]="its kkk kkk",
"ptB kkk kkk",
"kkk kkk ptB",
"kkk kkk kkk",
"kkk xxx ptW",
"kkk ptB kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"xxx xxx kkk",
"ptB kkk kkk",
"kkk kkk kkk",
"ptW kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"ptB kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk ptB kkk";
"kkk kkk kkk";
"kkk kkk kkk";

lv7[]="kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk its kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk xxx kkk",
"kkk kkk kkk",
"kkk itr kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk";

lv8[]="kkk ptW kkk",
"kkk kkk kkk",
"kkk its itr",
"kkk kkk kkk",
"kkk xxx ptB",
"kkk kkk kkk",
"kkk kkk ptW",
"xxx kkk kkk",
"kkk kkk ptW",
"kkk kkk kkk",
"ptB kkk kkk",
"kkk kkk kkk",
"ptW kkk kkk",
"kkk kkk kkk",
"kkk kkk kkk",
"ptB kkk kkk",
"kkk kkk kkk",
"kkk ptW kkk",
"kkk kkk kkk",
"kkk kkk kkk";

// lv9[]="kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk",
// "kkk kkk kkk";

